#!/bin/bash

set -e  # Exit on any error

# Get the directory where the script is located
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PROJECT_ROOT="$( cd "$SCRIPT_DIR/.." && pwd )"

# Check if we're in the right directory
if [ ! -f "$PROJECT_ROOT/package.json" ]; then
    echo "Error: package.json not found."
    exit 1
fi

cd "$PROJECT_ROOT"

# Check if Hardhat node is already running
if lsof -Pi :8545 -sTCP:LISTEN -t >/dev/null 2>&1 ; then
    lsof -ti:8545 | xargs kill -9 2>/dev/null || true
    sleep 2
fi

# Start Hardhat node in background
npx hardhat node > hardhat-node.log 2>&1 &
HARDHAT_PID=$!

# Wait for Hardhat node to be ready
for i in {1..10}; do
    if grep -q "Started HTTP and WebSocket JSON-RPC server" hardhat-node.log 2>/dev/null; then
        break
    fi
    sleep 1
done

if ! grep -q "Started HTTP and WebSocket JSON-RPC server" hardhat-node.log 2>/dev/null; then
    echo "Error: Failed to start Hardhat node"
    kill $HARDHAT_PID 2>/dev/null || true
    exit 1
fi

# Deploy contract
DEPLOY_OUTPUT=$(npx hardhat deploy --network localhost --message "Local Testing Environment" 2>&1)
CONTRACT_ADDRESS=$(echo "$DEPLOY_OUTPUT" | grep "Contract Address:" | awk '{print $3}')

if [ -z "$CONTRACT_ADDRESS" ]; then
    echo "Error: Failed to extract contract address"
    kill $HARDHAT_PID 2>/dev/null || true
    exit 1
fi

# Create .env.local file
cat > .env.local << EOF
# Local Testing Environment Configuration
# Auto-generated by start-local-env.sh on $(date)
CONTRACT_ADDRESS=$CONTRACT_ADDRESS
PRIVATE_KEY=0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80
ALCHEMY_URL=http://127.0.0.1:8545
PORT=3000
EOF

# Check if backend is already running
if lsof -Pi :3000 -sTCP:LISTEN -t >/dev/null 2>&1 ; then
    lsof -ti:3000 | xargs kill -9 2>/dev/null || true
    sleep 2
fi

# Start backend server in background
npm start > backend.log 2>&1 &
BACKEND_PID=$!

# Wait for backend to be ready
for i in {1..15}; do
    if curl -s http://localhost:3000/api/blockchain/message > /dev/null 2>&1; then
        break
    fi
    sleep 1
done

# Save PIDs to file for cleanup script
cat > .local-env-pids << EOF
HARDHAT_PID=$HARDHAT_PID
BACKEND_PID=$BACKEND_PID
EOF

# Display summary
echo ""
echo "Local environment ready:"
echo "  Hardhat:  http://127.0.0.1:8545 (PID: $HARDHAT_PID)"
echo "  Backend:  http://localhost:3000 (PID: $BACKEND_PID)"
echo "  Contract: $CONTRACT_ADDRESS"
echo ""
echo "Stop with: ./scripts/stop-local-env.sh"
echo ""
